language: node_js
node_js:
  - "0.12"
notifications:
  email: false
addons:
  code_climate:
    repo_token: 4ac7e075263b1faa82dfab1c8bfe1ec0c3b1724c460945aa334ec01a9b0f74ee
after_script:
  - npm run test-cov
  - codeclimate < coverage/lcov.info